git:
  paging:
    colorArg: always
    pager: delta --paging=never
os:
  editPreset: "nvim-remote"
  copyToClipboardCmd: echo -n {{text}} | clipboard --yank
keybinding:
  universal:
    copyToClipboard: <c-y>
  files:
    commitChanges: c
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.25
