[terminal.shell]
program = "wsl"
args = ["--cd", "~"]

[font]
size = 11.0
normal = { family = "UDEV Gothic 35NF", style = "Regular" }
offset = { x = 1, y = 1 }

[window]
dynamic_title = false
padding = { x = 8, y = 8 }

[keyboard]
bindings = [
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "I", mods = "Control", chars = "\u001b[105;5u" },
  { key = "M", mods = "Control", chars = "\u001b[109;5u" },
]
